### ISSUE TITLE
AttributeError: 'WarmupCosineLR' object has no attribute 'get_last_lr'

### ISSUE THREAD

**Issue by Echo0125** [modelscope/ms-swift#2256]
Training Qwen2vl-7B:
```python
swift sft \
  --model_type qwen2-vl-7b-instruct \
  --model_id_or_path ./checkpoints/Qwen2-VL-7B-Instruct \
  --sft_type full \
  --dataset ./data/swift_train.json \
  --ddp_backend nccl \
  --weight_decay 0.1 \
  --warmup_ratio 0.03 \
  --deepspeed default-zero2 \
  --batch_size 1 \
  --gradient_accumulation_steps 16 \
  --save_strategy epoch \
  --use_flash_attn True \
  --eval_steps 500 \
  --val_dataset ./data/swift_val.json \
  --save_total_limit 1 \
  --num_train_epochs 1 \
  --learning_rate 2e-5 \
  --lazy_tokenize true \
  --save_only_model true \
  --save_steps 5000
  ```
  
  My enviroment:
  ```bash
  transformers==4.45.2
  torch==2.2.0
  accelerate==1.1.0.dev0
  ```
  
  My Error:
  ```python
  Traceback (most recent call last):                                                                                                                                                             
  File "/usr/local/lib/python3.8/dist-packages/swift/cli/sft.py", line 5, in <module>                                                                                                          
    sft_main()                                                                                                                                                                                 
  File "/usr/local/lib/python3.8/dist-packages/swift/utils/run_utils.py", line 32, in x_main                                                                                                   
    result = llm_x(args, **kwargs)                                                                                                                                                             
  File "/usr/local/lib/python3.8/dist-packages/swift/llm/sft.py", line 529, in llm_sft                                                                                                         
    return trainer_train(args, model, template, train_dataset, val_dataset, callbacks=callbacks, msg=msg)                                                                                      
  File "/usr/local/lib/python3.8/dist-packages/swift/llm/sft.py", line 479, in trainer_train                                                                                                   
    trainer.train(training_args.resume_from_checkpoint)                                                                                                                                        
  File "/usr/local/lib/python3.8/dist-packages/swift/trainers/mixin.py", line 462, in train                                                                                                    
    res = super().train(resume_from_checkpoint, *args, **kwargs)                                                                                                                               
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 2052, in train                                                                                                   
    return inner_training_loop(                                                                                                                                                                
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 2467, in _inner_training_loop                                                                                    
    self._maybe_log_save_evaluate(tr_loss, grad_norm, model, trial, epoch, ignore_keys_for_eval)                                                                                               
  File "/usr/local/lib/python3.8/dist-packages/swift/trainers/mixin.py", line 527, in _maybe_log_save_evaluate                                                                                 
    logs['learning_rate'] = self._get_learning_rate()                                                                                                                                          
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer_pt_utils.py", line 918, in _get_learning_rate                                                                              
    last_lr = self.lr_scheduler.get_last_lr()[0]                                                                                                                                               
  File "/usr/local/lib/python3.8/dist-packages/accelerate/scheduler.py", line 86, in get_last_lr                                                                                               
    return self.scheduler.get_last_lr()                                                                                                                                                        
AttributeError: 'WarmupCosineLR' object has no attribute 'get_last_lr'
```

**Comment by Jintao-Huang** [comment]
降低一下accelerate版本

**Comment by Echo0125** [comment]
I lower the version from 1.1.0.dev0 to 0.34.0, but still get the error.

**Comment by Echo0125** [comment]
Done, I check deepspeed config and source code, ds will overwirte lr_scheduler, after upgrade deepspeed to 0.15.0, the issue is fixed.
